spring:
  application:
    name: SimpleTodoApp
  datasource:
    url: jdbc:postgresql://localhost:5432/TodoDB
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create